#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
command -v flutter >/dev/null || { echo 'Install Flutter 3.29.3 first.'; exit 1; }
# Platform binaries/wrappers are generated by the locally installed official SDK.
# Existing Dart and customized Android text files are preserved by flutter create.
# Temp generation avoids trusting --overwrite semantics across SDK versions.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
flutter create --project-name pazel --org ir.pazel --platforms=android,ios,web "$tmp/pazel"
python3 scripts/merge_platforms.py "$tmp/pazel"
flutter pub get
test -x android/gradlew || chmod +x android/gradlew
printf '\nNext: flutter analyze && flutter test && flutter run\n'
